repos:
- repo: https://github.com/mwouts/jupytext
  rev: v1.16.7  # CURRENT_TAG/COMMIT_HASH
  hooks:
  - id: jupytext
    args: [--set-formats, "ipynb,python//py:percent"]
    additional_dependencies: [ruff]
    types_or: [python, jupyter]
    exclude: ^scripts/
- repo: https://github.com/mwouts/jupytext
  rev: v1.16.7  # CURRENT_TAG/COMMIT_HASH
  hooks:
  - id: jupytext
    args: [--sync, --pipe, "ruff check --fix {}"]
    additional_dependencies: [ruff]
    types_or: [python, jupyter]
    exclude: ^scripts/
- repo: https://github.com/mwouts/jupytext
  rev: v1.16.7  # CURRENT_TAG/COMMIT_HASH
  hooks:
  - id: jupytext
    args: [--sync, --pipe, "ruff format {}"]
    additional_dependencies: [ruff]
    types_or: [python, jupyter]
    exclude: ^scripts/
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.9
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix]
      types_or: [python, jupyter]
    # Run the formatter.
    - id: ruff-format
      types_or: [python, jupyter]