[project]
name = "nitrate-upwelling"
version = "0.1.0"
readme = "README.md"
requires-python = ">3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "cartopy>=0.24.1",
    "cmocean>=4.0.3",
    "colorama>=0.4.6",
    "cycler>=0.12.1",
    "flox>=0.10.0",
    "gsw>=3.6.19",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "matplotlib>=3.10.1",
    "numpy>=2.1.3",
    "pandas>=2.2.3",
    "pycoare>=0.3.0",
    "scipy<=1.15.3",
    "statsmodels>=0.14.4",
    "sympy>=1.13.3",
    "tqdm>=4.67.1",
    "utide>=0.3.1",
    "xarray[accel,io,parallel]>=2025.1.2",
    "zarr<3.0.4",
]
authors = [{ name = "Andrew Scherer", email = "andrew@sourcedepth.com" }]
license = "MIT"

[tool.uv]
exclude-newer = "2025-06-30T00:00:00Z"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "FURB177", # implicit-cwd; Path.resolve() is necessary for relative paths in Python notebooks
    "CPY001",  # missing-copyright-notice; project is MIT licensed
    "ERA001",  # commented-out-code; can't be used with jupytext scripts
    "D100",    # undocumented-public-module; don't require docstring for jupytext scripts
    "INP001",  # implicit-namespace-package; don't enforce __init__.py files for jupytext scripts
    "T201",    # print; printing is fine in notebooks
    "RET504",  # Unnecessary assignment to `idx` before `return` statement; prefer explicit variable assignment for clarity
    "PLR2004", # Magic value used in comparison; need to fix in empirical model notebook, but too big for now
]


[tool.ruff.lint.isort]
known-local-folder = ["functions", "ttide_py", "ttide"]
