[project]
name = "analysis"
version = "0.1.0"
readme = "README.md"
requires-python = ">3.11"
dependencies = []
authors = [
    {name = "Andrew Scherer", email = "andrew@sourcedepth.com"}
]
license = "MIT"
